
name: dwpc_rnn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.10.5
  - numpy=2.2.6
  - pandas=2.3.1
  - scipy=1.15.3
  - tqdm=4.67.1
  - requests=2.32.5
  - networkx=3.4.2
  - seaborn=0.13.2
  - scikit-learn=1.7.1
  - statsmodels=0.14.5
  - plotnine=0.15.0
  - pytorch=2.5.1
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jupyterlab=4.4.6
  - notebook=7.4.5
  - pip
  - pip:
      - hetmatpy==0.1.0
      - hetnetpy==0.3.1
