name: dwpc_rnn
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib>=3.8.0
  - numpy>=1.26.0
  - pandas>=2.2.0
  - scipy>=1.12.0
  - tqdm>=4.66.0
  - requests>=2.31.0
  - pip
  - pip:
      - hetmatpy>=0.1.0
