
name: dwpc_rnn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jupyterlab=4.4.6
  - notebook=7.4.5
  - pip
  - pip:
      - hetmatpy==0.1.0
      - hetnetpy==0.3.1
